version: '2'
services:
  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=devcode
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - nodejs-mysql-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 15s
      retries: 10
  backend-api-service: 
    image: collaborative-core-nodejs:2.1
    restart: always
    ports:
      - 3031:3030
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  nodejs-mysql-db:
    driver: local
